PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	--email TEXT UNIQUE NOT NULL
	password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS todolist (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	completed DATETIME
	FOREING KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS task (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	description TEXT,
	priority INTEGER NOT NULL DEFAULT 0,
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	completed DATETIME
	FOREING KEY (todolist_id) REFERENCES todolists(id) ON DELETE CASCADE
);
