PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS tasks (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	description TEXT NOT NULL,
	priority INTEGER NOT NULL,
	created DATETIME NOT NULL,
	completed DATETIME NULL
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL
);
